### PR TITLE
email contact ?

### PR DESCRIPTION
**Pull request by darknodi**
email contact ?

### CODE REVIEW

**Comment by darknodi** [comment]
@Nat-As email contact ?

**Comment by Nat-As** [comment]
That is my GitHub.

James Andrews
Florida Polytechnic University
4700 Research Way, Lakeland 33805
C: 469.510.8060

________________________________

**Comment by Nat-As** [comment]
<jandrews7348@floridapoly.edu>

**Comment by Nat-As** [comment]
The latest stable release has already been posted to SOFWERX/dataglove. This is an experimental branch that has limited or no functionality, but rather functions as Pseudo-Code and should not be merged.

**Pull request closed without merging**
